name: Doxygen

on: [push]

jobs:
  doxygen:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate documentation
        run: doxygen Doxyfile
